// Generated by gencpp from file my_package/bot_pose.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE_MESSAGE_BOT_POSE_H
#define MY_PACKAGE_MESSAGE_BOT_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_package
{
template <class ContainerAllocator>
struct bot_pose_
{
  typedef bot_pose_<ContainerAllocator> Type;

  bot_pose_()
    : command()
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  bot_pose_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::my_package::bot_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_package::bot_pose_<ContainerAllocator> const> ConstPtr;

}; // struct bot_pose_

typedef ::my_package::bot_pose_<std::allocator<void> > bot_pose;

typedef boost::shared_ptr< ::my_package::bot_pose > bot_posePtr;
typedef boost::shared_ptr< ::my_package::bot_pose const> bot_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_package::bot_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_package::bot_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_package::bot_pose_<ContainerAllocator1> & lhs, const ::my_package::bot_pose_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_package::bot_pose_<ContainerAllocator1> & lhs, const ::my_package::bot_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_package::bot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_package::bot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::bot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_package::bot_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::bot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_package::bot_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_package::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73fdb5a9e2fcf473f35b1e1ab498b36d";
  }

  static const char* value(const ::my_package::bot_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73fdb5a9e2fcf473ULL;
  static const uint64_t static_value2 = 0xf35b1e1ab498b36dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_package::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_package/bot_pose";
  }

  static const char* value(const ::my_package::bot_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_package::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
;
  }

  static const char* value(const ::my_package::bot_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_package::bot_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_package::bot_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_package::bot_pose_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PACKAGE_MESSAGE_BOT_POSE_H
